/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ADMIN_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_API_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AWS_SES_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_SES_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": import("@cloudflare/workers-types").Service
    "AuthApi": import("@cloudflare/workers-types").Service
    "AuthStorage": import("@cloudflare/workers-types").KVNamespace
    "Bucket": import("@cloudflare/workers-types").R2Bucket
    "CLOUDFLARE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_DEFAULT_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_INCIDENT_WEBHOOK_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_SUPPORT_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_SUPPORT_CHANNEL_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "EMAILOCTOPUS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FEISHU_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FEISHU_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HONEYCOMB_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HoneycombWebhookSecret": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "R2AccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "R2SecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SALESFORCE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SALESFORCE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SALESFORCE_INSTANCE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "SUPPORT_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UpstashRedisRestToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UpstashRedisRestUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "WebApp": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}

import "sst"
export {}
