#!/usr/bin/env bun
import { $ } from "bun"
import pkg from "../package.json"
import { Script } from "@enthusjast/ustcode-script"
import { fileURLToPath } from "url"

const dir = fileURLToPath(new URL("..", import.meta.url))
process.chdir(dir)

async function published(name: string, version: string) {
  return (await $`npm view ${name}@${version} version`.nothrow()).exitCode === 0
}

async function publish(dir: string, name: string, version: string) {
  // GitHub artifact downloads can drop the executable bit.
  if (process.platform !== "win32") await $`chmod -R 755 .`.cwd(dir)
  if (await published(name, version)) {
    console.log(`already published ${name}@${version}`)
    return
  }
  await $`bun pm pack`.cwd(dir)
  await $`npm publish *.tgz --access public --tag ${Script.channel}`.cwd(dir)
}

const binaries: Record<string, string> = {}
// Platform packages live two levels deep under dist/@enthusjast/ustcode-<os>-<arch>/;
// a single-level glob misses them and the release would ship without any binary.
for (const filepath of new Bun.Glob("@enthusjast/*/package.json").scanSync({ cwd: "./dist" })) {
  const pkg = await Bun.file(`./dist/${filepath}`).json()
  binaries[pkg.name] = pkg.version
}
console.log("binaries", binaries)
const version = Object.values(binaries)[0]

await $`mkdir -p ./dist/${pkg.name}`
await $`mkdir -p ./dist/${pkg.name}/bin`
await $`cp ./script/postinstall.mjs ./dist/${pkg.name}/postinstall.mjs`
await Bun.file(`./dist/${pkg.name}/LICENSE`).write(await Bun.file("../../LICENSE").text())
await Bun.file(`./dist/${pkg.name}/bin/ustcode.exe`).write(
  [
    `echo "Error: ${pkg.name}'s postinstall script was not run." >&2`,
    'echo "" >&2',
    'echo "This occurs when using --ignore-scripts during installation, or when using a" >&2',
    'echo "package manager like pnpm that does not run postinstall scripts by default." >&2',
    'echo "" >&2',
    'echo "To fix this, run the postinstall script manually:" >&2',
    `echo "  cd node_modules/${pkg.name} && node postinstall.mjs" >&2`,
    'echo "" >&2',
    `echo "Or reinstall ${pkg.name} without the --ignore-scripts flag." >&2`,
    "exit 1",
    "",
  ].join("\n"),
)

await Bun.file(`./dist/${pkg.name}/package.json`).write(
  JSON.stringify(
    {
      name: pkg.name,
      bin: {
        ustcode: "./bin/ustcode.exe",
      },
      scripts: {
        postinstall: "node ./postinstall.mjs",
      },
      version: version,
      license: pkg.license,
      os: ["darwin", "linux", "win32"],
      cpu: ["arm64", "x64"],
      optionalDependencies: binaries,
    },
    null,
    2,
  ),
)

const tasks = Object.entries(binaries).map(async ([name]) => {
  await publish(`./dist/${name}`, name, binaries[name])
})
await Promise.all(tasks)
await publish(`./dist/${pkg.name}`, pkg.name, version)


async function sha256Hex(path: string): Promise<string> {
  // sha256sum is GNU coreutils (absent by default on macOS); shasum ships with
  // macOS's Perl and is usually present on Linux too.
  const sum = (await $`command -v sha256sum`.nothrow()).exitCode === 0 ? "sha256sum" : "shasum -a 256"
  const out = await $`${sum} ${path}`.text()
  return out.trim().split(/\s+/)[0]
}

if (!Script.preview) {
  // Calculate SHA values
  const arm64Sha = await sha256Hex("./dist/ustcode-linux-arm64.tar.gz")
  const x64Sha = await sha256Hex("./dist/ustcode-linux-x64.tar.gz")
  const macX64Sha = await sha256Hex("./dist/ustcode-darwin-x64.zip")
  const macArm64Sha = await sha256Hex("./dist/ustcode-darwin-arm64.zip")

  // Homebrew formula
  const homebrewFormula = [
    "# typed: false",
    "# frozen_string_literal: true",
    "",
    "# This file was generated by GoReleaser. DO NOT EDIT.",
    "class Ustcode < Formula",
    `  desc "The AI coding agent built for the terminal."`,
    `  homepage "https://github.com/Enthusjast/ustcode"`,
    `  version "${Script.version.split("-")[0]}"`,
    "",
    `  depends_on "ripgrep"`,
    "",
    "  on_macos do",
    "    if Hardware::CPU.intel?",
    `      url "https://github.com/Enthusjast/ustcode/releases/download/v${Script.version}/ustcode-darwin-x64.zip"`,
    `      sha256 "${macX64Sha}"`,
    "",
    "      def install",
    '        bin.install "ustcode"',
    "      end",
    "    end",
    "    if Hardware::CPU.arm?",
    `      url "https://github.com/Enthusjast/ustcode/releases/download/v${Script.version}/ustcode-darwin-arm64.zip"`,
    `      sha256 "${macArm64Sha}"`,
    "",
    "      def install",
    '        bin.install "ustcode"',
    "      end",
    "    end",
    "  end",
    "",
    "  on_linux do",
    "    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?",
    `      url "https://github.com/Enthusjast/ustcode/releases/download/v${Script.version}/ustcode-linux-x64.tar.gz"`,
    `      sha256 "${x64Sha}"`,
    "      def install",
    '        bin.install "ustcode"',
    "      end",
    "    end",
    "    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?",
    `      url "https://github.com/Enthusjast/ustcode/releases/download/v${Script.version}/ustcode-linux-arm64.tar.gz"`,
    `      sha256 "${arm64Sha}"`,
    "      def install",
    '        bin.install "ustcode"',
    "      end",
    "    end",
    "  end",
    "end",
    "",
    "",
  ].join("\n")

  const token = process.env.GITHUB_TOKEN
  if (token) {
    const tap = `https://x-access-token:${token}@github.com/Enthusjast/homebrew-tap.git`
    await $`rm -rf ./dist/homebrew-tap`
    await $`git clone ${tap} ./dist/homebrew-tap`
    await Bun.file("./dist/homebrew-tap/ustcode.rb").write(homebrewFormula)
    await $`cd ./dist/homebrew-tap && git add ustcode.rb`
    if ((await $`cd ./dist/homebrew-tap && git diff --cached --quiet`.nothrow()).exitCode !== 0) {
      await $`cd ./dist/homebrew-tap && git commit -m "Update to v${Script.version}"`
      await $`cd ./dist/homebrew-tap && git push`
    }
  } else {
    // A local release without a Homebrew tap token should still succeed; the
    // tap update is skipped (CI passes a token scoped to the tap repo).
    console.warn("GITHUB_TOKEN not set — skipping Homebrew tap update")
  }
}
